### ISSUE TITLE
Consider cloning from local repo

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/gradle-git-publish#1]
To make larger repos faster to clone, consider an approach like this (if `org.ajoberstar.grgit` is used):

1. Init fresh repo
1. Add remote for local `project.grgit` repo, fetch the target branch from there
1. Add remote for real origin repo and fetch the target branch from there
1. Reset/Create local branch to match origin

This would maybe save on network traffic pulling history from large repos.

**Comment by shevek** [comment]
Or the ability to clone a remote repo, but use a local "reference" repo for the first N commits, thus reducing the overall network traffic. Similar to some advanced repo engines which use bittorrent to pull the bulk of the repo, then use the normal repo protocol only to pull recent commits.

**Comment by ajoberstar** [comment]
You can try this in 2.1.0-beta.1. Check the README for the new property.

**Comment by ajoberstar** [comment]
Well someday, you'll be able to try it... Having trouble with Circle CI's downloads for the Gradle wrapper.
