### ISSUE TITLE
Plugin not able to publish github pages when gpg commit signature feature is enabled. 

### ISSUE THREAD

**Issue by bathulasai** [ajoberstar/gradle-git-publish#102]
Error:

org.eclipse.jgit.api.errors.ServiceUnavailableException: Signing service is not available

Temporary fix:

git config --global --unset commit.gpgsign

**Comment by ajoberstar** [comment]
This can be disabled via the plugin as well. However, I had forgotten to document it, but have now in https://github.com/ajoberstar/gradle-git-publish/commit/679113141888ed883dfcc71f15196cdf148bcfb5.

See #78
