### ISSUE TITLE
Undeclared build service deprecation when enabling stable configuration cache

### ISSUE THREAD

**Issue by ciscoo** [ajoberstar/gradle-git-publish#108]
With [stable configuration cache](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:stable) enabled in settings:

```kotlin
enableFeaturePreview("STABLE_CONFIGURATION_CACHE")
```

The following warning gets logged with `--warning-mode all`:

 > Task :documentation:gitPublishReset
Build service 'git-publish-main-grgit' is being used by task ':documentation:gitPublishReset' without the corresponding declaration via 'Task#usesService'. This behavior has been deprecated. This will fail with an error in Gradle 9.0. Declare the association between the task and the build service using 'Task#usesService'. Consult the upgrading guide for further information: https://docs.gradle.org/8.6-rc-2/userguide/upgrading_version_7.html#undeclared_build_service_usage
>
> Task :documentation:gitPublishCopy
>
> Task :documentation:gitPublishCommit
Build service 'git-publish-main-grgit' is being used by task ':documentation:gitPublishCommit' without the corresponding declaration via 'Task#usesService'. This behavior has been deprecated. This will fail with an error in Gradle 9.0. Declare the association between the task and the build service using 'Task#usesService'. Consult the upgrading guide for further information: https://docs.gradle.org/8.6-rc-2/userguide/upgrading_version_7.html#undeclared_build_service_usage
>
> Task :documentation:gitPublishPush
Build service 'git-publish-main-grgit' is being used by task ':documentation:gitPublishPush' without the corresponding declaration via 'Task#usesService'. This behavior has been deprecated. This will fail with an error in Gradle 9.0. Declare the association between the task and the build service using 'Task#usesService'. Consult the upgrading guide for further information: https://docs.gradle.org/8.6-rc-2/userguide/upgrading_version_7.html#undeclared_build_service_usage

**Comment by ciscoo** [comment]
Workaround:

```kotlin
tasks {
    val mainGrgitService = gradle.sharedServices.registrations["git-publish-main-grgit"].service
    gitPublishReset {
        usesService(mainGrgitService)
    }
    gitPublishCommit {
        usesService(mainGrgitService)
    }
    gitPublishPush {
        usesService(mainGrgitService)
    }
}
```

But this only works for the `main` publication. Custom publications would have to do the same for their own tasks.

**Comment by ajoberstar** [comment]
Hopefully 4.2.2 should take care of that. Thanks for reporting it!
