### ISSUE TITLE
Is there any limitation when using `GITHUB_TOKEN` from GitHub Actions secrets

### ISSUE THREAD

**Issue by Goooler** [ajoberstar/gradle-git-publish#109]
We use this plugin to deploy GH pages, providing credentials like:

```yml
# https://ajoberstar.org/grgit/main/grgit-authentication.html#_environment_variables
GRGIT_USER: ${{ secrets.GITHUB_TOKEN }}
```

but there is an auth issue:

```sh
Execution failed for task ':gitPublishPush'.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> org.eclipse.jgit.api.errors.TransportException: https://github.com/GradleUp/shadow.git: not authorized
```

Everything worked well when I ran this task again on my local device with my personal token. 

Is there anything I am missing?

See more details at:

- https://github.com/GradleUp/shadow/actions/runs/10296332607/job/28497520608
- https://github.com/GradleUp/shadow/blob/8ffe309dd2327f396d9f969371c554381bb66ba9/.github/workflows/release.yml#L28-L33
- https://github.com/GradleUp/shadow/blob/3b399392a3707bae78f74cb599c8c6534664430d/gradle/ghPages.gradle#L3-L17

**Comment by ajoberstar** [comment]
I'm not aware of any limitations using the Actions `GITHUB_TOKEN` outside of [assigning permissions on the job](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/assigning-permissions-to-jobs) (which I see you're already doing). Those `GITHUB_TOKEN`s are equivalent to fine-grained tokens, so you may be able to do some testing on your local device with one of those and play around with settings.

I would have suspected that `contents: write` would be enough. The other one that stands out as potentially needed is `pages: write`.

**Comment by Goooler** [comment]
Thanks for your response!

I tried, in my case, we must declare `GRGIT_USER` and `GRGIT_PASS`, see

- https://github.com/GradleUp/shadow/blob/45cf10ba89fc72e0e4c3bf129bad18eaaac67107/.github/workflows/ci.yml#L46-L67
- https://github.com/GradleUp/shadow/actions/runs/10361740142/job/28682576080

**Comment by ajoberstar** [comment]
Interesting, thanks for sharing the fix!

**Comment by Goooler** [comment]
Let me guess the reason, when using a token for `GRGIT_USER` we must ensure there is a Git user configured on the device, but it's not configured on GHA by default.

**Comment by ajoberstar** [comment]
I'm guessing that fine grained tokens like the GITHUB_TOKEN must be used as a password. I think I've seen `x-github-token` used in some other places. But maybe the user value is ignored by GitHub in this case.
