### ISSUE TITLE
Use the PropertyState API on the extension

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/gradle-git-publish#31]
The extension properties could probably all (for the non copyspec ones) be switched to use this. Though that would mean dropping support for Gradle <4.1.

**Comment by bmuschko** [comment]
FYI: `PropertyState` was introduced with Gradle 4.0.

**Comment by ajoberstar** [comment]
So far, doesn't seem like this buys anything for the properties I have. This plugin's pretty basic, so closing this out for now.
