### ISSUE TITLE
Plugin doesn't respect extension's repoDir property

### ISSUE THREAD

**Issue by dchesterman** [ajoberstar/gradle-git-publish#37]
When the createCopyTask is created during plugin#apply() the extension will not have been configured yet and the repoDir property used to configure the copy spec is not the proper path.  This results in the content always being copied into `gitPublish` but everything else is using the path configured in the extension's repoDir property.

```  
private Task createCopyTask(Project project, GitPublishExtension extension) {
    Task task = project.tasks.create(COPY_TASK, Copy)
    task.with {
      group = 'publishing'
      description = 'Copy contents to be published to git.'
      with extension.contents
      into extension.repoDir
    }
    return task
  }
```

I tested a fix and just changing `into extension.repoDir` to `into { extension.repoDir }` will fix this.

**Comment by dchesterman** [comment]
This actually applies to the extension `repo` as well.  The reset task configures the `repo`, but other tasks have already been configured with the unconfigured `repo` during plugin#apply...

hmmm maybe its not from being configured too early but something is off.  If you check out a new repo and try to publish right out of the gate it will fail and the git repo in the commit step is unconfigured

**Comment by ajoberstar** [comment]
Plan to get this fixed tonight. For the `repo` field, the other tasks only access it in the `doLast` block, so it doesn't get dereferenced until runtime (when reset has already run).
