### ISSUE TITLE
Pass result of exec command to gitPublish config

### ISSUE THREAD

**Issue by fviolette** [ajoberstar/gradle-git-publish#43]
I have a task get the short hash of the latest commit on a particular folder, which I would want to append to text of `commitMassage`.

```
def last = new ByteArrayOutputStream()
task getLastCommit {
    doLast {
        exec {
            workingDir = projectDir
            commandLine 'git', 'rev-parse', '--short', 'master', '--', 'test'
            standardOutput = last
        }
    }
}
```
However since this is configuration it does not work.
What would be the best way?

This is my current configuration:

```
gitPublish {
    repoUri = '<repo>'
    branch = 'gh-pages'
    contents {
        from 'out'
    }
    preserve {
        include '**/*'
    }
    commitMessage = "Deploy docs to gh-pages" 
}
```

I want commitMessage = "Deploy docs to gh-pages (" + `last` +")".

This is pretty basic I guess.

**Comment by ajoberstar** [comment]
You should be able to do this with [grgit](http://ajoberstar.org/grgit/grgit-gradle.html):

```groovy
commitMessage = "Deploy docs to gh-pages (${grgit.head().abbreviatedId})"
```

**Comment by fviolette** [comment]
Thanks, it does the job :+1:

**Comment by fviolette** [comment]
Hello,

This exact line seems not to work for me with recent releases (at least with 1.0.0 and grgit 2.2.1)

`Cannot set the value of a property of type java.lang.String using an instance of type org.codehaus.groovy.runtime.GStringImpl.`

**Comment by ajoberstar** [comment]
What version of Gradle?

**Comment by ajoberstar** [comment]
I can reproduce this on 4.3 and 4.8-rc-3, I'll open a new issue for this. (#50)
