### ISSUE TITLE
Provide alternative URI in example

### ISSUE THREAD

**Issue by mnlipp** [ajoberstar/gradle-git-publish#44]
Please save other people's lifetime and add another URI in the example on the README.md.

```
gitPublish {
    // where to publish to (repo must exist)
    repoUri = 'git@github.com/ajoberstar/test-repo.git'
    // (or 'https://github.com/ajoberstar/test-repo.git', depending on authentication)
    ...
```

I *know* that the information is in the [documentation](http://ajoberstar.org/grgit/grgit-authentication.html). But the relationship between authentication method and URI can only be derived from the example
section and besides, when you get there, you have long forgotten about the `repoUri` you copied before.

**Comment by ajoberstar** [comment]
Done. Thanks for pointing that out.
