### ISSUE TITLE
String properties on extension can't be set with a GString

### ISSUE THREAD

**Issue by ajoberstar** [ajoberstar/gradle-git-publish#50]
via @ fviolette 

> `commitMessage = "Deploy docs to gh-pages (${grgit.head().abbreviatedId})"`
>
> This exact line seems not to work for me with recent releases (at least with 1.0.0 and grgit 2.2.1)
>
> `Cannot set the value of a property of type java.lang.String using an instance of type org.codehaus.groovy.runtime.GStringImpl.`

**Comment by ajoberstar** [comment]
This is caused by gradle/gradle#3005.

**Comment by ajoberstar** [comment]
A similar discussion on a different Gradle plugin: bmuschko/gradle-docker-plugin#404

**Comment by ajoberstar** [comment]
I have mixed feelings on this, since I think it should really be a Gradle DSL improvement.

For now, I'm going to document this in the release notes of 0.4.0 and 1.0.0. It might be a little clunky, but you can get this to work as a user by calling `toString()`.

**Comment by fviolette** [comment]
Thanks for confirming and providing extensive information – converting to String works for now.
I'll be on the watch for similar issues within the core projects directly.

**Comment by cdancy** [comment]
I'm the current maintainer of the `gradle-docker-plugin` mentioned above and indeed this issue has hit our users more times than I can count now. It does feel like a gradle/groovy/dsl bug in that, at least in some cases, the proper marshaling is not being done when passing in values to pure java libraries. This happens more for us when the user is using a collection (set, list, map, etc) that contains instances of `GStringImpl`. The collection itself is passed correctly to the underlying java library/code but the references within are not proper Strings and so java flips out.

**Comment by ajoberstar** [comment]
@cdancy Thanks for chiming in here. What approach have you taken to this so far?

**Comment by cdancy** [comment]
@ajoberstar however unfortunate this sounds we ensure to do a `toString` on anything that gets passed to our backing java library. For collections we haven't done anything and have just been advising folks to `toString` all of their GStrings. We'll probably adopt an approach I've taken with other plugins I've written and have various utility methods that take in some collection type and return a new collection of the same type with all values having been toString'ed. I don't currently have a better solution and that seems to work when it's adopted at the added expense of having to do this every time we need to pass along a collection.

**Comment by ajoberstar** [comment]
@cdancy I poked around a little in your plugin and I think I see where you're doing this now. For this plugin, it seems to only be an issue on `Property<String>` types in the extension. I think this might require explicit setter methods that take a `String` (which would probably allow for Groovy's normal coercion to happen).

**Comment by cdancy** [comment]
@ajoberstar yeah if I had to take a guess it's with any type of collection or boxed type or something which acts as container. You could probably one-line this with groovy but [HERE](https://github.com/cdancy/gradle-artifactory-rest-plugin/blob/master/src/main/groovy/com/cdancy/gradle/artifactory/rest/utils/ArtifactoryRestUtil.groovy#L39) is a general idea of what I was talking about. I don't like it but it does work.

**Comment by ajoberstar** [comment]
Looks like this is going to be fixed in Gradle 5. See gradle/gradle#6536.

**Comment by cdancy** [comment]
Good find and hopefully it works.

**Comment by ajoberstar** [comment]
Now have a test that confirms this works on Gradle 5.
