### ISSUE TITLE
Unable to configure when using a Gitlab token as part of the URL

### ISSUE THREAD

**Issue by hirowla** [ajoberstar/gradle-git-publish#54]
I've put this question [here](https://stackoverflow.com/questions/50712148/unable-to-execute-gitpublish-tasks-when-accessing-gitlab-and-including-token-as) too but then realised this is a better place to ask.

Basically I don't know how to configure Gradle to using a Gitlab URL which includes an access token (hence it shouldn't need a username/password to access the repository). How would you configure gradle to do this? 

Thanks.

**Comment by ajoberstar** [comment]
I would suggest using a URL without the token included, and using username and/or password to provide the token. With GitHub tokens, I'm able to use either:

- username = token, password unset
- username = <username>, password = token

I would think one of those scenarios would work for GitLab as well.

I've never tested using the creds in the URL, so I don't know how JGit handles that, but there's far more risk of that URL being logged somewhere and exposing your token than if you provide the token via the credentials options.

**Comment by hirowla** [comment]
Thanks for the suggestion. The working combination is username = <username>, password = token.
