### ISSUE TITLE
Copying content into different subdirectories

### ISSUE THREAD

**Issue by bmuschko** [ajoberstar/gradle-git-publish#56]
I am using version 0.3.3 of the `gradle-git-publish` plugin. It seems that the plugin overwrites existing content if you declare to write it to different subdirectories.

```
gitPublish {
    repoUri = 'https://github.com/bmuschko/gradle-docker-plugin.git'
    branch = 'gh-pages'

    contents {
        from(groovydoc.outputs.files) {
            into 'api'
        }
        from("$asciidoctor.outputDir/html5") {
            into 'userguide'
        }
    }
}

gitPublishPush.dependsOn groovydoc, asciidoctor
```

The end result is a subdirectory `userguide`. The `api` subdirectory does not exist.

**Comment by ajoberstar** [comment]
I'm guessing this is a delegation issue. I have some working ones that do:

```groovy
gitPublish.contents.from('somewhere') {
  into 'wherever'
}
```

I presume I need another variant [here](https://github.com/ajoberstar/gradle-git-publish/blob/af6ec70d6aa013efa399e432cfab462fd1f89585/src/main/java/org/ajoberstar/gradle/git/publish/GitPublishExtension.java#L51) that takes a closure and does the delegate first strategy.

**Comment by ajoberstar** [comment]
As far as I can tell this is working now. I added a test in 465dee2, but it didn't fail. Maybe something that changed since 0.3.3? Please reopen if it's really still broken.
