### ISSUE TITLE
Add an option to create a shallow clone in gitPublishReset

### ISSUE THREAD

**Issue by marcphilipp** [ajoberstar/gradle-git-publish#57]
We use your excellent plugins to publish documentation and Javadoc to GH Pages in the junit5 repo. As you can see in this [build scan](https://scans.gradle.com/s/bk3ef7qeavuba/timeline?sort=duration), `gitPublishReset` takes most of the time of this build that was executed by a Travis job.

<img width="815" alt="screen shot 2018-09-29 at 18 23 38" src="https://user-images.githubusercontent.com/214207/46248080-debb3180-c414-11e8-9c56-6cfcdf30e584.png">

For our purposes a shallow clone of the single `gh-pages` branch would be sufficent to publish to our branch. This is probably not true for every project, but a configuration option that triggers the use of the grgit/JGit equivalent of `--single-branch --depth=1` would really speed up our build.

**Comment by marcphilipp** [comment]
Looks like it isn't possible with JGit at the moment... https://github.com/ajoberstar/grgit/issues/155

**Comment by shevek** [comment]
Similarly an option to clone using a local reference repository for the bulk of the data transfer might help?

**Comment by ajoberstar** [comment]
@shevek See #1  for the local repo idea. Seems like it could help a lot for bigger projects that already have that data cloned.

**Comment by liza-mae** [comment]
Any update on whether this will be supported?

**Comment by marcphilipp** [comment]
@ajoberstar Thanks for this! In JUnit's build, `gitPublishReset` went down from [3m 38s](https://ge.junit.org/s/4jbcpuhkoy6gm/timeline?details=odbtjiejdowby) to [1m 13s](https://ge.junit.org/s/oqcaaugo4utzc/timeline?details=odbtjiejdowby). 🎉

**Comment by ajoberstar** [comment]
Thanks to @AfzalivE for sending the original PR adding support to grgit!
