### ISSUE TITLE
Enhancement: Retries on gitPublishPush

### ISSUE THREAD

**Issue by benzvan** [ajoberstar/gradle-git-publish#62]
We have a situation where we can cause a race condition with multiple build processes publishing docs to the same repository. It would be great to have a retry option for failed pushes.

**Comment by benzvan** [comment]
Looking at the code, I'm not sure this is possible. It would have to restart from `gitPublishReset`

**Comment by ajoberstar** [comment]
Closing under the assumption this is resolved. If that's not true and you want to discuss further, please reopen.
