### ISSUE TITLE
GitPublishReset uses deprecated ProjectLayout.directoryProperty() method

### ISSUE THREAD

**Issue by cmuchinsky** [ajoberstar/gradle-git-publish#64]
With Gradle 5.0, getting the following warning that is coming from this plugin:
```
The ProjectLayout.directoryProperty() method has been deprecated. This is scheduled to be removed in Gradle 6.0. Please use the ObjectFactory.directoryProperty() method instead.
```

**Comment by ajoberstar** [comment]
Thanks for the report. I'll have to see if there's a way to maintain compatibility with Gradle 4 but stil eliminate the deprecation warning.

**Comment by Alex-Vol-SV** [comment]
@ajoberstar You can use the project.objects.directoryProperty() since version 4.0 in place of this to fix it.

**Comment by marcphilipp** [comment]
I've submitted #71 to address this issue.

**Comment by marcphilipp** [comment]
As far as I can see, `GitPublishReset` still uses the deprecated method, doesn’t it?

**Comment by ajoberstar** [comment]
Do you mean that you still get a deprecation warning when running it or that the commit doesn't look like the right change?

There is still a call to layout's directoryProperty but only if not on Gradle 5.

**Comment by cmuchinsky** [comment]
I am still seeing the warning with Gradle 5.3 even after upgrading to the 2.1.0 plugin version.

**Comment by marcphilipp** [comment]
There were two places that used the deprecated method: `GitPublishExtension` and `GitPublishReset`. You've only replaced the former in 739e3e6 while the latter is unchanged, isn't it?

**Comment by ajoberstar** [comment]
Ah, missed that there were two of these in your PR. Pushed up a 2.1.1-rc.1. Let me know if it's resolved now.

**Comment by cmuchinsky** [comment]
That seems to have fixed it for me

**Comment by ajoberstar** [comment]
Final 2.1.1 is out now.
