### ISSUE TITLE
Credential for accessing private repository

### ISSUE THREAD

**Issue by AdnanTheEntertainer** [ajoberstar/gradle-git-publish#74]
How and where to provide credential for cloning remote **private repository** on github

**Comment by DavideD** [comment]
I haven't tried it but I think you should follow the documentation here: http://ajoberstar.org/grgit/grgit-authentication.html

**Comment by ajoberstar** [comment]
Closing under the assumption this is resolved. If that's not true and you want to discuss further, please reopen.
