### ISSUE TITLE
Version 2.1.2 incompatible with Java 8

### ISSUE THREAD

**Issue by cmuchinsky** [ajoberstar/gradle-git-publish#77]
After upgrading from `2.1.1` to `2.1.2` I see the following error:

> org/ajoberstar/gradle/git/publish/GitPublishPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by cmuchinsky** [comment]
Any thoughts on this @ajoberstar?

**Comment by ajoberstar** [comment]
Releasing 2.1.3-rc.1 to fix this. Let me know if it works for you and I'll release the final.

**Comment by cmuchinsky** [comment]
Works for me, thx!

**Comment by heshamMassoud** [comment]
This also affects us here: https://github.com/commercetools/commercetools-sync-java/pull/470

@ajoberstar When will this be released?

**Comment by ajoberstar** [comment]
Released now
