### ISSUE TITLE
Provide a way to opt out of gpgsign

### ISSUE THREAD

**Issue by britter** [ajoberstar/gradle-git-publish#78]
I have commit signing enabled globally in [my git config](https://github.com/britter/dotfiles/blob/master/.gitconfig#L6-L7). When using this plugin, the `gitPublishCommit` task fails with `org.eclipse.jgit.api.errors.JGitInternalException: missing credentials provider`, because the gpg key I use for signing is password protected (see https://scans.gradle.com/s/hcmyry7guhezc/failure?openFailures=WzBd&openStackTraces=WzJd#top=0). As a work around I have added a task that modified the `.git/config` file inside the cloned repository and deactivates commit signing there. It would be great to have a configuration option on `GitPublishExtension` to deactivate commit signing.

**Comment by ajoberstar** [comment]
Yeah, this could be useful to expose. Likely won't get to this myself, but a PR would be welcome. Thanks for submitting this!

**Comment by ajoberstar** [comment]
There is a `sign` property on the `grgit.commit()`, if anyone looks at doing this.

**Comment by britter** [comment]
Here you go https://github.com/ajoberstar/gradle-git-publish/pull/80
