### ISSUE TITLE
Not possible to publish to two branches in one project

### ISSUE THREAD

**Issue by ysb33r** [ajoberstar/gradle-git-publish#86]
I have a use case where I push to to orphaned branches. Currently this is very hard in the way the plugin is authored. If would be nice is where is some way of adding additional grouping of tasks by convention i.e. 

```groovy
gitPublishSets.create 'foo'
```
and then configure
```
gitPublish {
  branch = 'pages'
}
gitPublishFoo {
  branch = 'foo'
}
```
and additional tasks are named `gitPublishFooReset`, `gitPublishFooCopy` etc.

**Comment by ysb33r** [comment]
Just to add, my current workaround is to add an additional subproject and then publish from there. The configuration in the subproject then has to be something like

```groovy
gitPublish {
    repoUri = rootProject.gitPublish.repoUri

    branch = 'foo'

    contents {
        from "${rootProject.buildDir}/docs/foo", {
            // ...
        }
    }

    commitMessage = "Update FOO for ${project.version}"
}

```

**Comment by ajoberstar** [comment]
Sure, so some way to configure multiple outputs. Maybe adding a NamedDomainObjectContainer that can cover the settings that are present on the current extension. Leave the existing settings as a proxy for configuring the `main` publication.

```groovy
gitPublish {
  // normal top level options
  publications {
    main {
      // same as top level
    }
    foo {
      // options to apply to gitPublishFoo<task>
    }
  }
}
```

**Comment by ajoberstar** [comment]
See the README for usage details. This is in `4.1.0-rc.1`. Let me know if you have any feedback.

**Comment by ysb33r** [comment]
@ajoberstar Thank you. I have finally started using this. It works really well.
