### ISSUE TITLE
Publish files to multiple target directories with the same from statement

### ISSUE THREAD

**Issue by bmuschko** [ajoberstar/gradle-git-publish#88]
It seems that the plugin doesn't properly handle the use case where you can define multiple `into` statements as a nested element of a `from` statement.

```
from('mydir') {
   into 'current'
   into '1.2.3'
}
```

This will only publish to the last definition of an `into` statement. In the code snippet above, `current` doesn't exist. This behavior is usually supported by a `CopySpec`. As a workaround, you have to define multiple `from` statements which leads to code duplication.

```
from('mydir') {
   into 'current'
}

from('mydir') {
   into '1.2.3'
}
```

**Comment by ajoberstar** [comment]
[I'm just directly passing](https://github.com/ajoberstar/gradle-git-publish/blob/3e0159ebf1379cc6e3f93483d5b75d9c45b37a8b/src/main/java/org/ajoberstar/gradle/git/publish/GitPublishExtension.java#L66-L68)  your `contents {}` block to a `CopySpec` retrieved from `project.copySpec()`, so seems like a limitation of the copy spec Gradle provides.

Feel free to reopen if there's a different Gradle API I should be accessing to handle that.
