### ISSUE TITLE
using plugin with kotlin dsl based

### ISSUE THREAD

**Issue by cheroliv** [ajoberstar/gradle-git-publish#91]
Hello, since I'm trying migration from groovy to kotlin dsl.
I face the problem concerning the non readability, of the plugin member to configure the git actions.
Here is, how I wrote in kotlin, my gitPublish task.
```
gitPublish {
    if (Constants.param_component == Constants.componentFlag.DEFAULT) {
        repoUri = properties["github_pages_blog_repository"] as Property<String>?
        branch = properties["git_branch"] as Property<String>?
        contents {
            from(file((properties["jbake_content_from"] as Property<String>?)!!)) {
                into((properties["jbake_content_to"] as Property<String>?)!!)
            }
        }
    }
}
```
Im using :
- java 15-open on opensuse tumbleweed
- gradle 6.7
- kotlin 1.4.10
- plugin git-publish 3.0.0-rc.1

The error message says repoUri and branch cannot be reassigned.
So what is the technique to get them populated with my values?

**Comment by vguignot-ingenico** [comment]
You can use this:



	gitPublish {	
		repoUri.set("https://xxx/toto.git")
		branch.set("master")
		repoDir.set(file("$buildDir/gitPublish"))
		contents {
			from(spmDir)
			into("./")
		}
		preserve {
			include("**/*")
			// exclude("/**")
		}
    	commitMessage.set("${rootProject.extra.get("jobBranch")}: commit from job ${rootProject.extra.get("jobUrl")}")
	}

**Comment by cheroliv** [comment]
I did not tried yet, but the problem was the cycle of initialisation who, does not allow to change field after construction. it means like setter not exists.
after my idea was to play more with init block.
kind of by extending the plugin task.
```
open class PrintHerokuVersion : Exec() {
    init {
        this.workingDir = project.rootDir
        this.commandLine("/snap/bin/heroku", "-v")
        this.standardOutput = ByteArrayOutputStream()
    }
}

project.tasks.register<PrintHerokuVersion>("printHerokuVersion")

project.tasks.withType<PrintHerokuVersion> {
    doLast { logger.info(standardOutput.toString()) }
}
```

But in the mean time, I leaved that part of the code in a parent build.gradle in groovy based dsl, and a build.gradle.kts children in kotlin with every plugin running well.
I will close the issue regarding to a hybride gradle multi build project solution.

**Comment by cheroliv** [comment]
> You can use this:
> 
> ```
> gitPublish {	
> 	repoUri.set("https://xxx/toto.git")
> 	branch.set("master")
> 	repoDir.set(file("$buildDir/gitPublish"))
> 	contents {
> 		from(spmDir)
> 		into("./")
> 	}
> 	preserve {
> 		include("**/*")
> 		// exclude("/**")
> 	}
> 	commitMessage.set("${rootProject.extra.get("jobBranch")}: commit from job ${rootProject.extra.get("jobUrl")}")
> }
> ```

Following your codes, It succeeds, Thanks a lot for the tips.
```
gitPublish {
    if (Constants.param_component == Constants.componentFlag.DEFAULT) {
        repoUri.set(properties["github_pages_blog_repository"] as String)
        branch.set(properties["git_branch"] as String)
        contents {
            from(file(properties["jbake_content_from"] as String)) {
                into((properties["jbake_content_to"] as String))
            }
        }
    }
}
```
