### ISSUE TITLE
gitPublishReset - Public key authentication failed.

### ISSUE THREAD

**Issue by mehdimahmoud** [ajoberstar/gradle-git-publish#94]
Using a GIT Azure repo (ssh.dev.azure.com:v3/{repo-path-project}).

1. Testing the ssh -vT git@ssh.dev.azure.com --> no error authentication
2. Testing git pull and git push on the same project  --> no error authentication without prompting as well

Do you know if we can get a better log to know which public key is used? (--debug mode does not provide more indication)

Currently issue:

* What went wrong:
Execution failed for task ':bridge:bridge:gitPublishReset'.
> ssh.dev.azure.com:v3/{repo-path-project}: remote: Public key authentication failed.

Did you already test it with Azure GIT syntax?

**Comment by ajoberstar** [comment]
Grgit currently handles SSH auth by falling back to your native `ssh` or `plink` executable, see [GrgitSystemReader](https://github.com/ajoberstar/grgit/blob/f64bf7c1febcd3289038c9b70b5000fea330e9f9/grgit-core/src/main/groovy/org/ajoberstar/grgit/auth/GrgitSystemReader.java#L127-L139). As such I don't if there's much logging we can do there. It does seem odd that it would work via CLI and fail in grgit given the intended behavior though.

**Comment by ajoberstar** [comment]
Closing as stale. Feel free to re-open if you have ideas on how we could troubleshoot this more.
