### ISSUE TITLE
Gradle 7 + Kotlin rewrite

### ISSUE THREAD

**Issue by elect86** [ajoberstar/gradle-git-publish#96]
Hey Andrew,

following the readme about contributions, I'd like to try to give this cool plugin a refresh by bumping to Gradle 7 and using kotlin for build scripts and source code (static typing + type safe accessors + DSL + nullability etc etc)

Also, I'd move all the `*.gradle` scripts into `buildSrc`

ps: why using dependencies locking without any dynamic dependency?

**Comment by ajoberstar** [comment]
Sorry for the long delay in responding to this. The JCenter to Maven Central migration was the big challenge at the time that was killing my enthusiasm. That's now resolved, so I'm not in need of a replacement maintainer, but if there are ideas of things you'd want to work on, please let me know.

**Comment by ajoberstar** [comment]
I'll close this issue, but feel free to comment, re-open, or open a new issue with a feature/fix idea.
